; vaultsign-signer.iss — Inno Setup script for the VaultSign Signer
; per-user Windows installer. Compiled by GitHub Actions on tag push and
; signed twice via Azure Trusted Signing (the inner helper before
; bundling, then the outer Setup.exe after compilation).
;
; AppVersion is injected at compile time:
;   iscc /DAppVersion=0.1.3 installer\vaultsign-signer.iss
;
; Without the /D flag we fall back to a sentinel "0.0.0-local" so that
; local builds compile but are obviously not real releases.

#ifndef AppVersion
  #define AppVersion "0.0.0-local"
#endif

#define AppName        "VaultSign Signer"
#define AppPublisher   "Rocket99 Ventures LLC"
#define AppHelpURL     "https://vaultsign.app"
#define HostExeName    "vaultsign-host.exe"
#define ManifestName   "com.vaultsign.signer.json"
#define ExtensionID    "daaihfchoifcjlkiiafinacokmmphnde"
#define StoreURL       "https://chrome.google.com/webstore/detail/" + ExtensionID

[Setup]
; AppId is a stable GUID that identifies the product family across versions.
; Do NOT change it once shipped — Windows uses it to detect upgrades.
AppId={{A633D90A-735D-4A89-9568-15E3D45BF692}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppHelpURL}
AppSupportURL={#AppHelpURL}
AppUpdatesURL={#AppHelpURL}
DefaultDirName={localappdata}\VaultSign\Signer
DefaultGroupName={#AppName}
DisableDirPage=yes
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=VaultSignSigner-Setup-{#AppVersion}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName={#AppName} {#AppVersion}
UninstallDisplayIcon={app}\{#HostExeName}
; English fallback if a future OS locale isn't bundled.
ShowLanguageDialog=auto

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "english";             MessagesFile: "compiler:Default.isl"

[InstallDelete]
; Wipe any pre-existing manifest from a previous (possibly aborted)
; install of the same product. The fresh manifest is written in [Code]
; below during ssInstall.
Type: files; Name: "{app}\{#ManifestName}"

[Files]
; The helper is staged into this directory by the CI workflow (or by the
; developer running a local build) before iscc.exe runs.
Source: "vaultsign-host.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; A non-technical user looking for "VaultSign Signer" in the Start Menu
; gets two entries: one that opens the help page in the default browser
; (will become /ajuda/icp-brasil once that page exists), and one that
; runs the uninstaller directly.
Name: "{group}\{#AppName}";             Filename: "{#AppHelpURL}"
Name: "{group}\Desinstalar {#AppName}"; Filename: "{uninstallexe}"

[Registry]
; Per-user Chrome Native Messaging registration.
;   - Root HKCU avoids admin rights.
;   - uninsdeletekey removes the key entirely when the user uninstalls.
Root: HKCU; Subkey: "Software\Google\Chrome\NativeMessagingHosts\com.vaultsign.signer"; \
    ValueType: string; ValueName: ""; ValueData: "{app}\{#ManifestName}"; \
    Flags: uninsdeletekey

[Run]
; Shown as a checkbox on the FinishedPage — defaults to checked. shellexec
; opens the URL in the user's default browser; nowait means the installer
; does not block waiting for Chrome to start.
Filename: "{#StoreURL}"; \
    Description: "Abrir Chrome Web Store para instalar a extensao"; \
    Flags: postinstall shellexec nowait

[UninstallDelete]
; The manifest JSON is generated by [Code] at install time, not copied by
; [Files], so Inno does not know it needs cleanup. Tell it explicitly.
Type: files;     Name: "{app}\{#ManifestName}"
Type: dirifempty; Name: "{app}"
Type: dirifempty; Name: "{localappdata}\VaultSign"

[Code]
// Writes the Chrome Native Messaging manifest with the absolute path to
// the freshly-installed helper. We escape backslashes for JSON encoding so
// Chrome's parser sees "C:\\Users\\..." not "C:\Users\...".
//
// Called from CurStepChanged(ssInstall) — Inno fires that step AFTER the
// {app} directory is created but BEFORE the InstallDelete/Files/Registry/
// Icons/Run sections are processed. So the manifest exists on disk by the
// time the registry section writes the HKCU pointer to it, eliminating
// the "registry exists, manifest missing" failure mode.
//
// If the write fails (disk full, permission denied, etc.) we Abort the
// install — Inno tears down anything already touched and the user is
// left with a clean machine.
procedure WriteNativeHostManifest();
var
  ManifestPath: string;
  HostPath:     string;
  JsonContent:  string;
begin
  HostPath := ExpandConstant('{app}\{#HostExeName}');
  StringChangeEx(HostPath, '\', '\\', True);

  ManifestPath := ExpandConstant('{app}\{#ManifestName}');

  JsonContent :=
    '{' + #13#10 +
    '  "name": "com.vaultsign.signer",' + #13#10 +
    '  "description": "VaultSign Native Signer Host",' + #13#10 +
    '  "path": "' + HostPath + '",' + #13#10 +
    '  "type": "stdio",' + #13#10 +
    '  "allowed_origins": [' + #13#10 +
    '    "chrome-extension://{#ExtensionID}/"' + #13#10 +
    '  ]' + #13#10 +
    '}' + #13#10;

  if not SaveStringToFile(ManifestPath, JsonContent, False) then
  begin
    MsgBox('Falha ao escrever o manifesto do Native Host em ' + ManifestPath +
           '. A instalacao sera cancelada para nao deixar um estado parcial.',
           mbCriticalError, MB_OK);
    Abort;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
    WriteNativeHostManifest();
end;
